### ISSUE TITLE
Unable to run  https://<hostname>. Browser not shows anything. Using docker swarm

### ISSUE THREAD

**Issue by ShriprasadM** [OpenVisualCloud/Ad-Insertion-Sample#236] opened 2020-06-18 14:28 UTC
1. able to up the dockers using make command
2. started docker swarm with init command
3. Launched the browser..

**Comment by xwu2git** [comment] 2020-06-18 17:22
Do you replace <hostname> in https://<< hostname >> with your docker swarm master hostname?
Do you see a security warning from the browser?

**Comment by ShriprasadM** [comment] 2020-06-19 03:12
Yes. I did that.
1. I have set up this on another machine
2. Trying to access `https://<< hostname >>` from my local machine
3. Following services are installed

<img width="1153" alt="image" src="https://user-images.githubusercontent.com/9314645/85092646-c225e500-b207-11ea-998f-ad1771b51981.png">

4. As it was not working, I did the following, 
Here I ran docker instance of  ssai_content_provider_frontend , but exposed internal port 8080 to outer port 80

`CONTAINER ID        IMAGE                                                     COMMAND                  CREATED             STATUS              PORTS                                    NAMES
1b3f067fa5ed        ssai_content_provider_frontend:latest                     "/bin/bash -c /home/…"   10 hours ago        Up 10 hours         0.0.0.0:80->8080/tcp                     laughing_williamson`

which resulted in n showing the UI as mentioned in README.md. But, Video URL is empty. Also I can not edit that. I could see some errors in the debug window.

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/9314645/85092952-88091300-b208-11ea-9c7b-9bee5f249a5f.png">

**Comment by xwu2git** [comment] 2020-06-19 03:47
Your service list showed that CDN was not up and running. Could you check what was the log message?

The CDN service is internally configured as https. Thus mapping it to port 80 will not work as is. Is it possible that your machine port 443 is occupied? In that case, please map the port to 8443 in the deployment script. Try to access it via https://<< hostname >>:8443.

**Comment by ShriprasadM** [comment] 2020-06-19 05:31
I have taken down custom installed docker instance as mentined in step#4. This was an extra step i did because, the thing as mentioned as per documentation is not showing anything in the browser.

Now there is
1. docker swarm instance is running
2. docker stack contains all *adi* services

I am new to the docker swarm. So not familiar with its architecture. sorry for that, but can you help me here. Following can be silly questions

Question
1. Why I still can't access it?
2. how https://<< hostname >>, docker swarm master node and *adi*services are related. who tells to render ad insertion landing page and how?
3. Do I need to start httpd instance?
4. As per https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/doc/cmake.md - start/stop_docker_compose not found.

**Comment by xwu2git** [comment] 2020-06-19 22:54
Here are the steps for browsers to see the URL:
(1) The CDN deployment script maps the external 443 port to an internal 8443 port. https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/deployment/docker-swarm/cdn.m4. This port talks https.
(2) The CDN nginx instance forwards the web request to the AD insertion service, which is at internal port 8080: https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/cdn/nginx.conf
(3) The AD insertion service forwards the web request to the content provider service, which is at internal port 8080: https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/ad-insertion/frontend/nginx.conf
(4) The content provider nginx instance handles the web request and returns the web pages: https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/content-provider/frontend/nginx.conf. 

For now, it's not clear why you don't see the web pages. Please do two experiments as follows. Please report the results:
(1) Change 443:8443 in this script to be "8443:8443": https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/deployment/docker-swarm/cdn.m4. Restart the app. See if you can see the web page at https://_hostname_:8443
(2) If you still cannot see it, please in addition, change: "listen 8443 ssl" to "listen 8443". https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/cdn/nginx.conf. Rebuild and restart the app. See if you can access the content via http://_hostname:8443.

**Comment by xwu2git** [comment] 2020-06-23 00:56
Any update?

**Comment by ShriprasadM** [comment] 2020-06-25 07:49
Thanks, @xwu2git, I will check today and update you

**Comment by ShriprasadM** [comment] 2020-06-25 11:43
`diff --git a/cdn/nginx.conf b/cdn/nginx.conf
index de0806c..044a5d5 100644
--- a/cdn/nginx.conf
+++ b/cdn/nginx.conf
@@ -17,7 +17,7 @@ http {
     limit_conn_zone $binary_remote_addr zone=addr2:10m;
 
     server {
-        listen 8443 ssl;
+        listen 8443;
         server_name _;
         client_body_timeout 5s;
         client_header_timeout 5s;
diff --git a/deployment/docker-swarm/cdn.m4 b/deployment/docker-swarm/cdn.m4
index 4fd3250..c4dbc57 100644
--- a/deployment/docker-swarm/cdn.m4
+++ b/deployment/docker-swarm/cdn.m4
@@ -2,7 +2,7 @@
     cdn-service:
         image: defn(`REGISTRY_PREFIX')ssai_cdn_service:latest
         ports:
-            - "443:8443"
+            - "8443:8443"
         environment:
             NO_PROXY: "*"
             no_proxy: "*"
`

**Comment by ShriprasadM** [comment] 2020-06-25 11:47
1. Did the following changes
2. rebuild application using https://github.com/OpenVisualCloud/Ad-Insertion-Sample#build 
3. started docker swarm using https://github.com/OpenVisualCloud/Ad-Insertion-Sample#startstop-services
4. Accessed http://<host>:8443 . still getting an error, can not connect to the server
5. ` Ad-Insertion-Sample]$ curl "http://localhost:8443"
curl: (7) Failed connect to localhost:8443; Connection refused` when tried from command line on same machine. getting connection refused error


diff --git a/cdn/nginx.conf b/cdn/nginx.conf
index de0806c..044a5d5 100644
--- a/cdn/nginx.conf
+++ b/cdn/nginx.conf
@@ -17,7 +17,7 @@ http {
     limit_conn_zone $binary_remote_addr zone=addr2:10m;
     server {
-        listen 8443 ssl;
+        listen 8443;
         server_name _;
         client_body_timeout 5s;
         client_header_timeout 5s;
diff --git a/deployment/docker-swarm/cdn.m4 b/deployment/docker-swarm/cdn.m4
index 4fd3250..c4dbc57 100644
--- a/deployment/docker-swarm/cdn.m4
+++ b/deployment/docker-swarm/cdn.m4
@@ -2,7 +2,7 @@
     cdn-service:
         image: defn(`REGISTRY_PREFIX')ssai_cdn_service:latest
         ports:
-            - "443:8443"
+            - "8443:8443"
         environment:
             NO_PROXY: "*"
             no_proxy: "*"`

**Comment by ShriprasadM** [comment] 2020-06-25 14:39
Hello @xwu2git , 
I am now able the issue page not loading. But now facing the same issue (see above browser screen with firebug) .. getting 404 for js and map files

0/1 replica  issue was occurring because was getting this error "Err": "starting container failed: linux spec user: unable to find user docker: no matching entries in passwd file", in case of  adi_cdn-service. The reason mostly is this file `https://github.com/OpenVisualCloud/Ad-Insertion-Sample/blob/master/cdn/Dockerfile` . it searches for the user `docker` , which is missing i gues in base image `ssai_common`.  Not sure how it works with other services

Please, guide me around that path mapping issue

**Comment by xwu2git** [comment] 2020-06-25 15:11
I think I found the issue. Did you build as root? Could you try to build it as a regular user instead? 
The root cause is "USER ${USER}" in the Dockerfile. If build as root, the user "docker" is not added during the build stage thus cannot be found during runtime. It will be fine if you build as a regular user. 
I will fix this issue. Stay tuned.

**Comment by xwu2git** [comment] 2020-06-25 15:16
Fixed in #240.

**Comment by ShriprasadM** [comment] 2020-06-25 16:26
@xwu2git , yes I am building this using sudo access for enabling setting up this application docker images. 

As discussed above, I am facing now another issue  of path mapping in case of js and map files (see screenshot as pasted earlier https://github.com/OpenVisualCloud/Ad-Insertion-Sample/issues/236#issuecomment-646411052)

**Comment by xwu2git** [comment] 2020-06-25 16:30
Sorry, can we start from the beginning? The issues are compounded together. 
After applying #240, do you see the homepage? The CDN instance is now running? Not 0/1 in docker stack services adi. Is the video list showing up?

**Comment by xwu2git** [comment] 2020-06-25 16:35
Also, how many nodes are there in your docker swarm? If it's more than 1, you need to share the volume folder on all worker nodes as described in deployment/docker-swarm/README.md. If it's a single node, then there is no specific setup needed other than docker swarm init.

**Comment by ShriprasadM** [comment] 2020-06-26 05:01
1. I haven't taken the latest pull including #240 yet as I an see the homepage now. 
2. Yes CDN instance is now running, showing 1/1 in docker stack services ad
3. On the homepage, I can see the playlist. But still now getting video URL and video played. Here is screenshot
    
<img width="1393" alt="image" src="https://user-images.githubusercontent.com/9314645/85822321-39272480-b798-11ea-849b-a5599be1d2ae.png">

4. As you can see above screenshot, I am now facing the path mapping issues. Right now it is for some of the js and .map files. It is returning 404 errors. Looking for help around it! Thanks!

**Comment by xwu2git** [comment] 2020-06-26 05:38
There is no map file in the repo. The error does not impact playing back. 
Did you double click on the videos?

**Comment by ShriprasadM** [comment] 2020-06-26 05:44
Checking

**Comment by ShriprasadM** [comment] 2020-06-26 05:47
Oh...  it is playing the video after selecting from the playlist. Better if we can mention it in documentation
It's working now! Thanks!

One question

1. Is this code Open source.
2. Is it production-ready? we are working on some POC using it

**Comment by xwu2git** [comment] 2020-06-26 05:47
Good.

**Comment by ShriprasadM** [comment] 2020-06-26 05:48
One question

Is this code Open source ? 
Is it production-ready? we are working on some POC using it ?

**Comment by xwu2git** [comment] 2020-06-26 13:32
Yes, it's fully open sourced. 
The ad-insertion feature is validated. However, this is a sample. Certain features are intentionally simplified, such as user account management, AD content management, AD decision making, as well as security designs. You might want to enhance those in a product.

**Comment by ShriprasadM** [comment] 2020-06-26 13:55
Thanks @xwu2git  for update !

**Comment by ShriprasadM** [comment] 2020-07-06 08:58
Hello @xwu2git , can we stitch multiple ads within single cue point here

**Comment by xwu2git** [comment] 2020-07-06 16:11
Yes, it is possible. In practice, you need to pay attention to resolution change during serving multiple ads. All ads of all resolutions of a cue point must be prepared as an atomic operation, or ad-falling back may kick in.

**Comment by ShriprasadM** [comment] 2020-07-08 16:32
Is this supports VAST capabilities

**Comment by xwu2git** [comment] 2020-07-08 23:04
We followed similar concept as VAST but did not follow the exact syntax, which is a bit overkill for this small sample. You can easily modify the code to use VAST.

**Comment by ShriprasadM** [comment] 2020-07-09 08:13
thanks  !

**Comment by QuPengfei** [comment] 2020-08-25 10:11
closed.

**Closed as completed by QuPengfei** 2020-08-25 10:11 UTC
